#+title: Orthogonalizing Variables in a Regression
#+author: Matt Brigida
#+PROPERTY: header-args  :eval yes
#+setupfile: ./darksun.theme

#+begin_comment
darksun theme
https://gitlab.com/OlMon/org-themes/-/raw/master/src/darksun/darksun.theme?ref_type=heads

See list of org themes here: https://olmon.gitlab.io/org-themes/

Can access all themes in .emacs/org-themes
#+end_comment

* Motivation

Say we want to include two correlated variables as explanatory variables in a regression.  Doing this causes =multicollinearity=, which does not bias coefficients however does increase coefficient standard errors. Note, you can for excessive multicollinearity with variance inflation factors.  To remove the correlation between the variables we can use a process refered to as /orthogonalization/ in the finance literature.  We describe this process in the example below.

* Example

#+begin_src R :session r :results nil :exports code
library(quantmod)
#+end_src


#+begin_src R :session r :results nil :exports code
market <- getSymbols("spy", auto.assign = FALSE)
oil <- getSymbols("uso", auto.assign = FALSE)
ng <- getSymbols("ung", auto.assign = FALSE)
#+end_src

#+begin_src R :session r :results nil :exports both
  data <- merge.xts(Delt(Cl(oil)), Delt(Cl(ng)), Delt(Cl(market)), join="inner")[-1,]
  names(data) <- c("oil", "ng", "market")
  tail(data)
#+end_src

#+RESULTS:
|   0.0315190832861485 |  0.0464744309819454 | -0.00215393057592739 |
|  0.00592276801701153 |  -0.040581980828226 |   0.0120917756409302 |
| -0.00254251883943779 |  0.0271348890529679 |   0.0248655549103136 |
|  0.00160991072052741 | -0.0163170194261311 |   0.0077321458684938 |
|  -0.0204929859850502 | -0.0102685715645954 |  0.00433172235740953 |
|  -0.0299466004958637 |   0.101356782508288 | 0.000952886744834291 |


#+begin_src R :session r :results nil :exports both
cor(data$oil, data$ng)
#+end_src

#+RESULTS:
: 0.16688267808796


#+begin_src R :session r :results nil :exports both
oil_orthogonalized <- lm(data$oil ~ data$ng)$resid
#+end_src

#+RESULTS:

#+begin_src R :session r :results nil :exports both
cor(oil_orthogonalized, data$ng)
#+end_src

#+RESULTS:
: 4.1870964646196e-17

Which is computer for 0.  Now there is no correlation between crude oil and natural gas, and we can run the following regression without worrying about the effect of multicollinearity.


#+begin_src R :session r :results t :exports both
summary(lm(data$market ~ oil_orthogonalized + data$ng))
#+end_src

#+RESULTS:
## Coefficients:
##                     Estimate Std. Error t value Pr(>|t|)    
## (Intercept)        0.0004347  0.0001755   2.477   0.0133 *  
## oil_orthogonalized 0.1965857  0.0075897  25.902  < 2e-16 ***
## data$ng            0.0409667  0.0058139   7.046 2.12e-12 ***
## ---
## Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
## 
## Residual standard error: 0.01167 on 4420 degrees of freedom
## Multiple R-squared:  0.1402,	Adjusted R-squared:  0.1398 
## F-statistic: 360.3 on 2 and 4420 DF,  p-value: < 2.2e-16
 
